spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
  servlet:
    multipart:
      max-file-size: 10MB  		# 设置单个文件最大大小为10MB
      max-request-size: 100MB
  redis:
    timeout:
       connection: 10000
       socket: 20000
    port: 6379
    host: localhost

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

minio:
  endpoint: http://127.0.0.1:9090
  accessKey: admin
  secretKey: 12345678
  bucketName: wcs

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8081/xxl-job-admin
    accessToken: default_token
    executor:
      appname: my-wcs
  ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
  ### xxl-job executor server-info
      ip:
      port: 3366
  ### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
  ### xxl-job executor log-retention-days
      logretentiondays: 30


